DROP DATABASE IF EXISTS `DATA TYPES 2`;
CREATE DATABASE `DATA TYPES 2`;
USE `DATA TYPES 2`;
CREATE TABLE `DATA` (
ID SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
`NAME` VARCHAR(50) NOT NULL,
BIRTH_DATE DATE NOT NULL,
GENDER ENUM('0','1','NULL'),-- (0 là male, 1 là female, null là unknow)
ISDELETEDFLAG BIT NOT NULL-- (0 là đang hoạt động, 1 là đã xóa--) 
);
